package com.example.alarm

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import com.example.data.AppStore

class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != Intent.ACTION_BOOT_COMPLETED &&
            intent.action != "android.intent.action.LOCKED_BOOT_COMPLETED") return

        val now = System.currentTimeMillis()

        try {
            // Re-arm every still-future manual reminder and drop the stale ones.
            // Shift reminders are regenerated by WorkScheduleScheduler below.
            val future = AppStore.getReminders(context).filter { it.triggerMs > now }
            AppStore.saveReminders(context, future)
            future.filter { it.kind != "shift" }.forEach { r ->
                armAlarm(context, r.requestCode, r.triggerMs, r.title, r.message, r.ringtoneUri, r.insistent)
            }

            // Top the work-schedule reminder window back up after reboot.
            WorkScheduleScheduler.sync(context)
        } catch (_: Exception) {}
    }
}
